use clap::Parser;
use flatten::vendor::{self, VendorOptions, VendoredPackage};
use flatten::{FlattenError, FlattenedPackage, ModuleTreeNode, TargetSelector, parse_target};
use miette::Result;
use std::{
    ffi::OsString,
    fs,
    io::{self, Write},
    path::{Path, PathBuf},
    process::{Command, Stdio},
};
use tracing::{Level, info, warn};

#[derive(Parser)]
#[command(
    version,
    about = "Flatten a Rust crate's source tree into a single .rs file"
)]
struct Args {
    /// Path to the directory of the package you want to flatten
    #[arg(default_value = ".")]
    package: PathBuf,

    /// Output file path. Defaults to `<target-name>.rs` in the current
    /// directory. Pass `-` (or use `--stdout`) to write to stdout.
    #[arg(short, long)]
    out: Option<PathBuf>,

    /// Write the flattened source to stdout instead of a file.
    #[arg(long, conflicts_with = "out")]
    stdout: bool,

    /// Parse and resolve everything, but don't write anything. Reports the
    /// size of what would have been written.
    #[arg(long)]
    check: bool,

    /// Suppress the "Generated by flatten" header banner. Useful when
    /// piping output into another tool that wants pure source.
    #[arg(long, alias = "bare")]
    no_banner: bool,

    /// Print a directory-tree summary of every inlined source file
    /// (path, byte size, line count) instead of writing the flat output.
    #[arg(long, conflicts_with = "fmt")]
    tree: bool,

    /// Pipe the output through `rustfmt` before writing. Requires rustfmt
    /// on PATH (`rustup component add rustfmt`). Honors the source crate's
    /// `rustfmt.toml` / `.rustfmt.toml` if present.
    #[arg(long)]
    fmt: bool,

    /// Strip comments and collapse runs of blank lines from the output.
    /// Always correctness-safe (comments and blank lines have no semantic
    /// meaning); meaningfully shrinks vendored output. Composes with
    /// `--vendor`, `--stdout`, `--out`, and `--check`. Mutually exclusive
    /// with `--fmt` (rustfmt would just re-add whitespace) and `--tree`.
    #[arg(long, conflicts_with_all = ["fmt", "tree"])]
    minify: bool,

    /// Read-only reconnaissance: classify the dependency graph as
    /// vendorable / unvendorable and print a report. Does not flatten,
    /// vendor, or write any output. See VENDORING.md.
    #[arg(long, conflicts_with_all = ["out", "stdout", "check", "tree", "fmt", "vendor"])]
    vendor_report: bool,

    /// Inline vendorable transitive deps into the flat output as
    /// `mod <crate_name>` blocks at the crate root. Refuses (in strict
    /// mode) on any dep that can't be vendored — proc-macros, build
    /// scripts, native links, feature-gated cfgs, `$crate` macros, etc.
    /// See VENDORING.md.
    #[arg(long, conflicts_with = "tree")]
    vendor: bool,

    /// Skip vendoring this dep — keep it as a `use foo::...` reference
    /// in the output. The user must provide it via Cargo.toml when
    /// compiling. Repeatable. Matches by crate name (all versions).
    ///
    /// Cuts the BFS at named deps: anything reachable ONLY through an
    /// --external dep is also dropped from the output (cargo brings it
    /// in transitively when the user lists the external in Cargo.toml).
    /// Anything reachable through a non-external path is still vendored.
    ///
    /// See EXTERNAL.md.
    #[arg(
        long = "external",
        value_name = "NAME",
        action = clap::ArgAction::Append,
        requires = "vendor"
    )]
    external: Vec<String>,

    /// Read external crate names from a file, one per line. Blank lines
    /// and `#`-prefixed comments (full-line or trailing) are ignored.
    /// Repeatable; combines additively with `--external NAME` flags and
    /// other `--external-file` arguments.
    #[arg(
        long = "external-file",
        value_name = "PATH",
        action = clap::ArgAction::Append,
        requires = "vendor"
    )]
    external_file: Vec<PathBuf>,

    /// Use a baked-in curated external list shipped with flatten.
    /// Currently the only preset is `infra` — covers
    /// signal-hook(-registry), winapi*, windows-sys/-targets, the per-
    /// arch `windows_*` packages, crossterm_winapi, serde_core, zmij.
    /// Repeatable; combines additively with `--external NAME` and
    /// `--external-file PATH`.
    #[arg(
        long = "external-preset",
        value_name = "NAME",
        action = clap::ArgAction::Append,
        requires = "vendor"
    )]
    external_preset: Vec<String>,

    /// Externalise the entire transitive cone of every `--external` /
    /// `--external-file` entry. Useful when an external dep shares a
    /// transitive (e.g. `serde_core` under `serde`) with a vendored
    /// crate — without this flag the shared transitive is vendored
    /// alongside, producing two copies in the final binary which can
    /// cause type-mismatch errors when the cargo-built external and the
    /// vendored copy meet at an API boundary. With this flag, the shared
    /// transitive is also kept external; vendored crates that reference
    /// it get auto-promoted to a "Required" Cargo.toml entry. See
    /// EXTERNAL.md.
    #[arg(long, requires = "vendor")]
    external_deep: bool,

    /// Legacy aggressive mode for `--external-deep`: every transitive
    /// dep of every external becomes external, even when reachable
    /// from vendored crates via non-external paths. Vendored crates
    /// that directly reference a now-cut transitive get auto-promoted
    /// to a "Required" Cargo.toml entry. Implies `--external-deep`.
    /// Pre-fix this was the default behavior of `--external-deep`;
    /// kept as opt-in for users who want their `Cargo.toml` to list
    /// every cut transitive instead of vendoring them.
    #[arg(long, requires = "vendor")]
    external_deep_aggressive: bool,

    /// Run the user crate's source through `flatten_expand` (a
    /// separate nightly binary) which inlines third-party proc-macro
    /// expansions — `#[derive(Serialize)]`, `#[tokio::main]`, etc. —
    /// directly into the source. Stdlib macros (println!, derive(Debug),
    /// vec!) are left as-is. Each proc-macro crate consumed by this
    /// expansion is automatically excluded from vendoring. Requires
    /// `flatten_expand` on PATH, or via $FLATTEN_EXPAND, or
    /// built at expand/target/debug/.
    #[arg(long, requires = "vendor")]
    expand: bool,

    /// Extend `--expand` to every vendored dep too, not just the user
    /// crate. Uses cargo's RUSTC_WRAPPER hook so each dep is expanded in
    /// its real compilation context (extern flags, edition, features).
    /// Implies `--expand`.
    #[arg(long, requires = "expand")]
    expand_deep: bool,

    /// Flatten the library target.
    #[arg(long, group = "target")]
    lib: bool,

    /// Flatten the named bin target.
    #[arg(long, value_name = "NAME", group = "target")]
    bin: Option<String>,

    /// Flatten the named example.
    #[arg(long, value_name = "NAME", group = "target")]
    example: Option<String>,

    /// Flatten the named integration test.
    #[arg(long, value_name = "NAME", group = "target")]
    test: Option<String>,

    /// Each repetition lowers the log level once. Default is INFO; with --quiet, ERROR.
    #[arg(short, long, action = clap::ArgAction::Count)]
    verbose: u8,

    /// Set the log level to ERROR (suppress INFO messages).
    #[arg(short, long, action = clap::ArgAction::SetTrue)]
    quiet: bool,
}

impl Args {
    fn selector(&self) -> TargetSelector {
        if self.lib {
            TargetSelector::Lib
        } else if let Some(n) = &self.bin {
            TargetSelector::Bin(n.clone())
        } else if let Some(n) = &self.example {
            TargetSelector::Example(n.clone())
        } else if let Some(n) = &self.test {
            TargetSelector::Test(n.clone())
        } else {
            TargetSelector::Auto
        }
    }
}

pub fn main() -> Result<()> {
    // When invoked as `cargo flatten ...`, cargo passes "flatten" as argv[1].
    let mut argv: Vec<OsString> = std::env::args_os().collect();
    if argv.get(1).is_some_and(|a| a == "flatten") {
        argv.remove(1);
    }
    let args = Args::parse_from(argv);

    configure_logging(&args);

    if args.vendor_report {
        let report = flatten::vendor::report(&args.package)?;
        let stdout = io::stdout();
        let mut handle = stdout.lock();
        write!(handle, "{report}").map_err(io_err("writing vendor report"))?;
        return Ok(());
    }

    let (mut buf, banner, kind_str, target_name) = if args.vendor {
        // User-typed `--external NAME` entries — typos here produce a
        // warning so users notice mismatches.
        let external: std::collections::HashSet<String> = args.external.iter().cloned().collect();
        // Curated-source entries (`--external-file`, `--external-preset`).
        // These intentionally cover more crates than any single project
        // uses, so unmatched names DO NOT warn.
        let mut external_silent: std::collections::HashSet<String> =
            std::collections::HashSet::new();
        for path in &args.external_file {
            let contents = fs::read_to_string(path).map_err(io_err(format!(
                "Failed reading --external-file `{}`",
                path.display()
            )))?;
            for name in flatten::external_file::parse_external_file(&contents) {
                external_silent.insert(name);
            }
        }
        for name in &args.external_preset {
            let contents = match name.as_str() {
                "infra" => include_str!("../presets/infra.txt"),
                "codingame" => include_str!("../presets/codingame.txt"),
                _ => {
                    return Err(FlattenError::other(format!(
                        "Unknown --external-preset `{name}`; known: infra, codingame"
                    ))
                    .into());
                }
            };
            for entry in flatten::external_file::parse_external_file(contents) {
                external_silent.insert(entry);
            }
        }
        let opts = VendorOptions {
            strict: true,
            external,
            external_silent,
            external_deep: args.external_deep,
            external_deep_aggressive: args.external_deep_aggressive,
            expand: args.expand,
            expand_deep: args.expand_deep,
        };
        let pkg = vendor::vendor_package(&args.package, &args.selector(), &opts)?;
        if args.tree {
            return print_tree_vendored(&pkg);
        }
        let mut body = Vec::new();
        write_vendored_body(&mut body, &pkg).expect("writing to Vec is infallible");
        // Final post-pass: drop `pub use crate::SIBLING::NAME;` items
        // referencing names absent from SIBLING (typically a macro that
        // was stripped when its proc-macro crate got auto-externalized
        // and inlined). Runs whenever any proc-macro was auto-inlined,
        // including under plain `--vendor` (no `--expand`) where
        // proc-macros get classified Unvendorable directly.
        body = vendor::scrub_assembled(body, &pkg);
        let banner = if args.no_banner {
            Vec::new()
        } else {
            let mut b = Vec::new();
            write_vendored_banner(&mut b, &pkg).expect("writing to Vec is infallible");
            b
        };
        (body, banner, pkg.kind.as_str().to_string(), pkg.target_name)
    } else {
        let pkg = parse_target(&args.package, &args.selector())?;
        if args.tree {
            return print_tree(&pkg);
        }
        let mut body = Vec::new();
        write_plain_body(&mut body, &pkg).expect("writing to Vec is infallible");
        let banner = if args.no_banner {
            Vec::new()
        } else {
            let mut b = Vec::new();
            write_plain_banner(&mut b, &pkg).expect("writing to Vec is infallible");
            b
        };
        (body, banner, pkg.kind.as_str().to_string(), pkg.target_name)
    };

    if args.fmt {
        buf = format_with_rustfmt(buf, &args.package)?;
    }

    if args.minify {
        let s = String::from_utf8(buf).map_err(|e| FlattenError::Io {
            context: "minifier input was not valid UTF-8".to_string(),
            source: io::Error::new(io::ErrorKind::InvalidData, e),
        })?;
        buf = flatten::minify::minify(&s).into_bytes();
    }

    // Banner is prepended after post-processing so --minify doesn't strip
    // it as just-another-comment block.
    if !banner.is_empty() {
        let mut combined = Vec::with_capacity(banner.len() + buf.len());
        combined.extend_from_slice(&banner);
        combined.extend_from_slice(&buf);
        buf = combined;
    }

    // Drain cfg-skipped mods accumulated during file loading. These
    // are mods that couldn't be inlined because the target file is
    // missing on the current build target (or its inner #![cfg(...)]
    // excludes this target). The flat output replaces them with
    // `{ /* cfg-skipped */ }` body comments — code that REFERENCES
    // those mod's symbols downstream will get unhelpful "cannot find
    // type X" errors. Surface a summary so the user can connect the
    // dots.
    let skipped = flatten::drain_skipped_mods();
    if !skipped.is_empty() {
        warn_skipped_mods_summary(&skipped);
    }

    if args.check {
        info!(
            "flatten --check: would write {} bytes ({} `{}`)",
            buf.len(),
            kind_str,
            target_name
        );
        return Ok(());
    }

    write_to_destination(&buf, &args, &target_name)?;
    Ok(())
}

fn warn_skipped_mods_summary(skipped: &[flatten::SkippedMod]) {
    use std::collections::BTreeMap;
    // Group by parent crate (deduce from the file path's cargo
    // registry segment, or the directory if no registry path).
    let mut by_crate: BTreeMap<String, Vec<&flatten::SkippedMod>> = BTreeMap::new();
    for s in skipped {
        let key = parent_crate_name(&s.declared_in);
        by_crate.entry(key).or_default().push(s);
    }
    let total = skipped.len();
    eprintln!();
    eprintln!(
        "flatten: {total} module(s) skipped due to cfg gates that exclude \
         this build target. Downstream cargo-build may emit `cannot find ...` \
         errors referring to these names:"
    );
    for (krate, mods) in &by_crate {
        for m in mods {
            eprintln!("    {krate}: mod {} — {}", m.mod_name, m.reason);
        }
    }
    eprintln!("Workarounds:");
    eprintln!("  - Re-run on the target where these mods resolve (different OS, etc.)");
    eprintln!("  - `--external <CRATE>` for the affected dep(s); user adds to their Cargo.toml");
    eprintln!();
}

fn parent_crate_name(file_path: &Path) -> String {
    // Two path shapes to handle:
    //  - cargo cache: `.../registry/src/index.crates.io-HASH/foo-1.2.3/src/lib.rs`
    //  - --expand-deep dump: `.../flatten_expand-PID/foo/src/lib.rs`
    //
    // Strategy: find a component named `src` (or `tests`, etc.) and
    // take the component immediately before it. Strip a `-VERSION`
    // suffix if present (cargo cache layout).
    let comps: Vec<_> = file_path.components().collect();
    for (i, c) in comps.iter().enumerate() {
        if let std::path::Component::Normal(name) = c
            && let Some(s) = name.to_str()
            && matches!(s, "src" | "tests" | "examples" | "benches")
            && i > 0
            && let Some(std::path::Component::Normal(prev)) = comps.get(i - 1)
            && let Some(prev_s) = prev.to_str()
        {
            // Cargo cache: `foo-1.2.3` → `foo`. Dump dir: `foo` → `foo`.
            if let Some(dash) = prev_s.rfind('-')
                && prev_s[dash + 1..]
                    .chars()
                    .next()
                    .is_some_and(|c| c.is_ascii_digit())
            {
                return prev_s[..dash].to_string();
            }
            return prev_s.to_string();
        }
    }
    file_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("?")
        .to_string()
}

fn print_tree(pkg: &FlattenedPackage) -> Result<()> {
    let tree = pkg.source.tree(pkg.entry_path.display().to_string());
    let stdout = io::stdout();
    let mut handle = stdout.lock();
    let mut do_print = || -> io::Result<()> {
        writeln!(handle, "{} ({}):", pkg.crate_name, pkg.kind.as_str())?;
        render_tree(&tree, "", true, true, &mut handle)?;
        writeln!(
            handle,
            "\nTotal: {} across {} files",
            fmt_bytes(tree.total_bytes()),
            tree.total_files()
        )
    };
    do_print().map_err(io_err("writing tree to stdout"))?;
    Ok(())
}

fn write_to_destination(buf: &[u8], args: &Args, target_name: &str) -> Result<()> {
    if args.stdout || args.out.as_deref().is_some_and(|p| p.as_os_str() == "-") {
        let stdout = io::stdout();
        let mut handle = stdout.lock();
        handle.write_all(buf).map_err(io_err("writing to stdout"))?;
        handle.flush().map_err(io_err("flushing stdout"))?;
        return Ok(());
    }

    let out_path = args
        .out
        .clone()
        .unwrap_or_else(|| PathBuf::from(format!("{target_name}.rs")));
    if let Some(parent) = out_path.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent).map_err(io_err(format!(
            "Failed creating output directory `{}`",
            parent.display()
        )))?;
    }
    fs::write(&out_path, buf)
        .map_err(io_err(format!("Failed writing `{}`", out_path.display())))?;
    info!("Wrote flattened source to `{}`", out_path.display());
    Ok(())
}

/// Pipe `input` through `rustfmt --emit=stdout`. If rustfmt isn't on PATH,
/// errors. If rustfmt rejects the input (parse failure, etc.), warns and
/// returns the unformatted input so the user still gets *something*.
fn format_with_rustfmt(input: Vec<u8>, crate_root: &Path) -> Result<Vec<u8>> {
    let mut cmd = Command::new("rustfmt");
    cmd.arg("--emit=stdout").arg("--edition=2024");

    // Use the source crate's rustfmt config if present so the formatted
    // output matches whatever the rest of that crate uses.
    for cfg in [
        crate_root.join("rustfmt.toml"),
        crate_root.join(".rustfmt.toml"),
    ] {
        if cfg.is_file() {
            cmd.arg("--config-path").arg(&cfg);
            break;
        }
    }

    cmd.stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());

    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) if e.kind() == io::ErrorKind::NotFound => {
            return Err(FlattenError::other(
                "rustfmt not found on PATH. Install with \
                 `rustup component add rustfmt`, or omit --fmt.",
            )
            .into());
        }
        Err(e) => {
            return Err(FlattenError::Io {
                context: "spawning rustfmt".to_string(),
                source: e,
            }
            .into());
        }
    };

    // Drain stdout AND stderr concurrently while writing stdin. With
    // both pipes piped, the parent is otherwise vulnerable to a
    // deadlock when rustfmt's stdout buffer (~64KB) fills before stdin
    // is fully written: rustfmt blocks on stdout, parent blocks on
    // stdin. Vendored output is 100k+ LOC where this triggers reliably.
    let mut stdin = child.stdin.take().expect("piped");
    let mut stdout = child.stdout.take().expect("piped");
    let mut stderr = child.stderr.take().expect("piped");
    let stdout_thread = std::thread::spawn(move || {
        let mut buf = Vec::new();
        std::io::Read::read_to_end(&mut stdout, &mut buf).map(|_| buf)
    });
    let stderr_thread = std::thread::spawn(move || {
        let mut buf = Vec::new();
        std::io::Read::read_to_end(&mut stderr, &mut buf).map(|_| buf)
    });
    let write_result = stdin.write_all(&input);
    drop(stdin); // signal EOF to rustfmt
    write_result.map_err(io_err("writing to rustfmt stdin"))?;

    let stdout_bytes = stdout_thread
        .join()
        .map_err(|_| FlattenError::other("rustfmt stdout reader thread panicked"))?
        .map_err(io_err("reading rustfmt stdout"))?;
    let stderr_bytes = stderr_thread
        .join()
        .map_err(|_| FlattenError::other("rustfmt stderr reader thread panicked"))?
        .map_err(io_err("reading rustfmt stderr"))?;
    let status = child.wait().map_err(io_err("waiting on rustfmt"))?;
    let output = std::process::Output {
        status,
        stdout: stdout_bytes,
        stderr: stderr_bytes,
    };

    if output.status.success() {
        Ok(output.stdout)
    } else {
        let stderr = String::from_utf8_lossy(&output.stderr);
        warn!(
            "rustfmt rejected the output ({}); falling back to unformatted source.\n{}",
            output.status,
            stderr.trim()
        );
        Ok(input)
    }
}

fn write_vendored_banner<W: Write>(w: &mut W, pkg: &VendoredPackage) -> io::Result<()> {
    use flatten::vendor::ExternalReason;

    writeln!(
        w,
        "// Generated by flatten --vendor from `{}` v{} ({}).",
        pkg.crate_name,
        pkg.crate_version,
        pkg.kind.as_str()
    )?;
    writeln!(w, "// Do not edit by hand — re-run flatten to refresh.")?;
    writeln!(
        w,
        "// Compile with: rustc --edition={} <this-file>.rs",
        edition_str(pkg.max_edition)
    )?;
    writeln!(
        w,
        "// For minimum binary size: add `-C lto=fat -C opt-level=z`."
    )?;
    if !pkg.vendored.is_empty() {
        writeln!(w, "//")?;
        writeln!(w, "// Vendored deps:")?;
        for d in &pkg.vendored {
            writeln!(w, "//   {} {}", d.name, d.version)?;
        }
    }

    // Group externals by reason for the banner.
    let unvendorable: Vec<_> = pkg
        .external
        .iter()
        .filter_map(|d| match &d.reason {
            ExternalReason::Unvendorable(rs) => Some((d, rs.join(", "))),
            ExternalReason::VendorFailed(r) => Some((d, r.clone())),
            _ => None,
        })
        .collect();
    let user_excluded: Vec<_> = pkg
        .external
        .iter()
        .filter(|d| matches!(d.reason, ExternalReason::UserExcluded))
        .collect();
    let required: Vec<_> = pkg
        .external
        .iter()
        .filter_map(|d| match &d.reason {
            ExternalReason::Required { because } => Some((d, because.clone())),
            _ => None,
        })
        .collect();

    if !unvendorable.is_empty() {
        writeln!(w, "//")?;
        writeln!(w, "// External requirements (could not vendor):")?;
        for (d, reasons) in &unvendorable {
            writeln!(w, "//   {} {} — {}", d.name, d.version, reasons)?;
        }
    }
    if !user_excluded.is_empty() {
        writeln!(w, "//")?;
        writeln!(w, "// Excluded by --external (you provide via Cargo.toml):")?;
        for d in &user_excluded {
            writeln!(w, "//   {} {}", d.name, d.version)?;
        }
    }
    if !required.is_empty() {
        writeln!(w, "//")?;
        writeln!(
            w,
            "// Required by vendored deps — also add to your Cargo.toml so"
        )?;
        writeln!(
            w,
            "// extern-prelude resolution finds the same copy cargo brings in"
        )?;
        writeln!(w, "// transitively (avoids double-vendoring):")?;
        for (d, because) in &required {
            writeln!(
                w,
                "//   {} {}  (used by vendored: {})",
                d.name,
                d.version,
                because.join(", ")
            )?;
        }
    }

    // If anything ended up external, append a build instruction footer.
    if !pkg.external.is_empty() {
        writeln!(w, "//")?;
        writeln!(w, "// To compile:")?;
        writeln!(
            w,
            "//   1. Create a Cargo.toml with the External + Excluded + Required items"
        )?;
        writeln!(w, "//      as direct dependencies.")?;
        writeln!(w, "//   2. Place this file at src/main.rs (or src/lib.rs).")?;
        writeln!(w, "//   3. cargo build.")?;
    }

    writeln!(w)?;
    Ok(())
}

fn write_vendored_body<W: Write>(w: &mut W, pkg: &VendoredPackage) -> io::Result<()> {
    if !pkg.vendored.is_empty() {
        // Suppress lints that would otherwise fail vendored code under
        // newer rustc. Each lint here has fired in real-world vendoring:
        //   - `dangerous_implicit_autorefs` — allocator-api2's raw-pointer
        //     code (`(*ptr).len()`) became hard-error in nightly 2024+.
        //   - `unused_imports` — our per-file sibling injection
        //     intentionally over-imports to satisfy macro expansions.
        //   - `unknown_lints` — older deps suppress lints that don't
        //     exist on the user's toolchain.
        // Inner attributes must precede every item, including
        // `extern crate`, so this goes first.
        writeln!(
            w,
            "#![allow(unknown_lints, dangerous_implicit_autorefs, unused_imports)]"
        )?;
    }
    let mut std_libs: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for d in &pkg.vendored {
        for lib in &d.extern_std_libs {
            std_libs.insert(lib.as_str());
        }
    }
    for lib in &std_libs {
        writeln!(w, "extern crate {lib};")?;
    }
    if !std_libs.is_empty() {
        writeln!(w)?;
    }
    write!(w, "{}", pkg.user_source)?;
    for d in &pkg.vendored {
        writeln!(w)?;
        writeln!(w, "pub mod {} {{", flatten::vendor::to_ident(&d.name))?;
        // Lift `#[macro_export]` macros to the vendored mod's root so
        // callers reach them as `<crate>::<macro>!()`. The original
        // `#[macro_export]` attribute lifted them to the user's crate
        // root, but we strip that during rewriting (otherwise it would
        // collide with the user's macros).
        //
        // The `pub(crate) use` statements must come AFTER any leading
        // inner attributes / `//!` doc comments — those have to be the
        // first items in the mod body (E0753 "expected outer doc
        // comment" otherwise).
        let dep_src = d.source.to_string();
        let inject_at = flatten::vendor::safe_inject_point(&dep_src);
        write!(w, "{}", &dep_src[..inject_at])?;
        for stmt in &d.macro_exports {
            writeln!(w, "{stmt}")?;
        }
        write!(w, "{}", &dep_src[inject_at..])?;
        writeln!(w, "\n}}")?;
    }
    Ok(())
}

fn print_tree_vendored(pkg: &VendoredPackage) -> Result<()> {
    let stdout = io::stdout();
    let mut handle = stdout.lock();
    writeln!(
        handle,
        "{} ({}) — vendored:",
        pkg.crate_name,
        pkg.kind.as_str()
    )
    .map_err(io_err("writing tree"))?;
    for d in &pkg.vendored {
        writeln!(handle, "  vendored: {} {}", d.name, d.version).map_err(io_err("writing tree"))?;
    }
    for d in &pkg.external {
        writeln!(handle, "  external: {} {}", d.name, d.version).map_err(io_err("writing tree"))?;
    }
    Ok(())
}

fn write_plain_banner<W: Write>(w: &mut W, pkg: &FlattenedPackage) -> io::Result<()> {
    if pkg.crate_name == pkg.target_name {
        writeln!(
            w,
            "// Generated by flatten from `{}` ({}).",
            pkg.crate_name,
            pkg.kind.as_str()
        )?;
    } else {
        writeln!(
            w,
            "// Generated by flatten from `{}` ({}: `{}`).",
            pkg.crate_name,
            pkg.kind.as_str(),
            pkg.target_name
        )?;
    }
    writeln!(w, "// Do not edit by hand — re-run flatten to refresh.")?;
    writeln!(w)?;
    Ok(())
}

fn write_plain_body<W: Write>(w: &mut W, pkg: &FlattenedPackage) -> io::Result<()> {
    write!(w, "{}", pkg.source)
}

fn edition_str(e: cargo_metadata::Edition) -> &'static str {
    match e {
        cargo_metadata::Edition::E2015 => "2015",
        cargo_metadata::Edition::E2018 => "2018",
        cargo_metadata::Edition::E2021 => "2021",
        cargo_metadata::Edition::E2024 => "2024",
        _ => "2024",
    }
}

fn io_err(context: impl Into<String>) -> impl FnOnce(io::Error) -> FlattenError {
    let context = context.into();
    move |e| FlattenError::Io { context, source: e }
}

fn render_tree<W: Write>(
    node: &ModuleTreeNode,
    prefix: &str,
    is_last: bool,
    is_root: bool,
    out: &mut W,
) -> io::Result<()> {
    let connector = if is_root {
        ""
    } else if is_last {
        "└── "
    } else {
        "├── "
    };
    writeln!(
        out,
        "{}{}{} ({}, {} LOC)",
        prefix,
        connector,
        node.display_path,
        fmt_bytes(node.bytes),
        node.lines
    )?;
    let new_prefix = if is_root {
        String::new()
    } else if is_last {
        format!("{prefix}    ")
    } else {
        format!("{prefix}│   ")
    };
    let last_idx = node.children.len().saturating_sub(1);
    for (i, child) in node.children.iter().enumerate() {
        render_tree(child, &new_prefix, i == last_idx, false, out)?;
    }
    Ok(())
}

fn fmt_bytes(n: usize) -> String {
    if n < 1024 {
        format!("{n} B")
    } else if n < 1024 * 1024 {
        format!("{:.1} KB", n as f64 / 1024.0)
    } else {
        format!("{:.1} MB", n as f64 / (1024.0 * 1024.0))
    }
}

fn configure_logging(args: &Args) {
    let level = match (args.quiet, args.verbose) {
        (true, 0) => Level::ERROR,
        (true, _) => Level::WARN,
        (false, 0) => Level::INFO,
        (false, 1) => Level::DEBUG,
        (false, _) => Level::TRACE,
    };
    tracing_subscriber::fmt()
        .with_max_level(level)
        .with_target(false)
        .without_time()
        .with_writer(std::io::stderr)
        .init();
}
