//! True end-to-end test: flatten the real tron C++ stdio bot (the
//! same `main.cpp` cargo builds via `tron_baseline_cpp`), compile the
//! result with the system C++ compiler, run the produced binary, and
//! verify it speaks the wire format correctly.
//!
//! This is the assertion that matters most for the CodinGame workflow:
//! "does the flattened file actually paste-and-compile?" If the layout
//! of the cgio headers or the `main.cpp` driver changes in a way that
//! breaks flattening, this test fails loudly.
//!
//! The test is auto-skipped (with a clear message) if no C++ compiler
//! is available — CI images without a toolchain shouldn't fail here.

use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::sync::Once;

use tempfile::TempDir;

static BUILD_DEFS: Once = Once::new();

/// `tron_defs.h` is cbindgen-generated by `tron_defs/build.rs`. Make
/// sure it exists before the flattener tries to read it — the `_defs`
/// crate doesn't appear in `cpp_flatten`'s dep graph so cargo won't
/// build it for us.
fn ensure_defs_header() {
    BUILD_DEFS.call_once(|| {
        let mut cmd = Command::new(env!("CARGO"));
        cmd.args(["build", "-p", "tron_defs"]);
        if !cfg!(debug_assertions) {
            cmd.arg("--release");
        }
        let status = cmd.status().expect("invoke cargo build for tron_defs");
        assert!(status.success(), "cargo build of tron_defs failed");
    });
}

fn workspace_root() -> PathBuf {
    // cpp_flatten/ lives at <ws>/crates/cpp_flatten/.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent() // <ws>/crates
        .and_then(std::path::Path::parent) // <ws>
        .expect("cpp_flatten crate is at <ws>/crates/cpp_flatten")
        .to_path_buf()
}

fn cxx_compiler() -> String {
    std::env::var("CXX").unwrap_or_else(|_| "c++".to_string())
}

fn compiler_available() -> bool {
    Command::new(cxx_compiler())
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

#[test]
fn tron_main_flattens_compiles_and_runs() {
    if !compiler_available() {
        eprintln!("skipping: no C++ compiler found (set CXX to override the default `c++`)",);
        return;
    }
    ensure_defs_header();

    let entry = workspace_root()
        .join("games")
        .join("tron")
        .join("bots")
        .join("baseline_cpp")
        .join("main.cpp");

    let flat = cpp_flatten::flatten(&entry).expect("flatten tron main");

    // Sanity-check the flattened text before we hand it to the
    // compiler — these are the substantive structural assertions.
    assert!(
        !flat.contains("#include \""),
        "flattened output still has local includes:\n{flat}",
    );
    assert!(
        flat.contains("#include <iostream>"),
        "flattened output dropped a system include",
    );
    assert!(
        flat.contains("int main()"),
        "flattened output is missing `int main()` — the CodinGame entry point",
    );
    // The `#ifdef CGIO_RUST_SHIM` branch still appears in the flat
    // text because the flattener doesn't evaluate `#if`s — the real
    // proof that the *right* branch is picked is the compile + run
    // below (we compile without -DCGIO_RUST_SHIM, so the standalone
    // `int main()` survives preprocessing).

    let tmp = TempDir::new().expect("create tempdir");
    let cpp_path = tmp.path().join("bot.cpp");
    let bin_path = tmp.path().join("bot");
    std::fs::write(&cpp_path, &flat).expect("write flattened cpp");

    // Compile. -O0 keeps the test fast; the production build's flags
    // aren't what we're testing here.
    let compile = Command::new(cxx_compiler())
        .args(["-std=c++20", "-O0", "-o"])
        .arg(&bin_path)
        .arg(&cpp_path)
        .output()
        .expect("invoke compiler");
    assert!(
        compile.status.success(),
        "compile failed:\nstdout: {}\nstderr: {}\nflattened source ({} bytes):\n{}",
        String::from_utf8_lossy(&compile.stdout),
        String::from_utf8_lossy(&compile.stderr),
        flat.len(),
        flat,
    );

    // Drive the bot with one tick of input. Tron wire format:
    //   <num_players> <player_number>
    //   <x1 y1 x2 y2>     ← one line per player, N total
    //   ...
    // The bot's strategy is `TurnOutput::default()` (UP).
    let mut child = Command::new(&bin_path)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn flattened bot");
    {
        let mut stdin = child.stdin.take().expect("piped stdin");
        write!(stdin, "2 0\n0 0 5 5\n10 10 15 15\n").expect("write turn input");
        // dropping stdin closes the pipe → bot sees EOF after its reply
    }
    let out = child.wait_with_output().expect("await bot");
    assert!(
        out.status.success(),
        "bot exited non-zero: stderr={}",
        String::from_utf8_lossy(&out.stderr),
    );
    let stdout = String::from_utf8(out.stdout).expect("utf-8 stdout");
    assert_eq!(
        stdout.trim_end(),
        "UP",
        "wrong move on opening tick (stdout={stdout:?})",
    );
}
