pub mod engine;

pub use engine::{
    BotStatus, Defs, NoInitialInput, NoInitialInputFfi, NoInitialInputRef, TurnResult, WireInput,
    WireInputFfi, WireOutput,
};

// ============================================================
//  Counter emission (FFI bots, Rust side)
// ============================================================
//
// Each loaded plugin links its own copy of `common` (as an rlib), so
// `COUNTER_CALLBACK` is a per-plugin static — no cross-plugin
// interference even though we use a global. The bot's
// `set_counter_callback` (generated by `ffi_bot!`) stores the
// runner-supplied function pointer here; `emit_counter` reads it
// lock-free on every call and short-circuits when null.
//
// AtomicPtr is the standard "function-pointer global" idiom: store
// the fn pointer's address atomically, transmute back on read. Both
// `Acquire` and `Release` orderings let us avoid a mutex on the
// emit hot path (counter emissions can happen many times per turn
// for bots that count nodes or TT probes).

use std::sync::atomic::{AtomicPtr, Ordering};

static COUNTER_CALLBACK: AtomicPtr<()> = AtomicPtr::new(std::ptr::null_mut());

/// Internal. Called by the `set_counter_callback` symbol that
/// `ffi_bot!` generates. Don't call from bot code — use the macro.
#[doc(hidden)]
pub fn __set_counter_callback(cb: Option<engine::CounterFn>) {
    let ptr = match cb {
        Some(f) => f as *mut (),
        None => std::ptr::null_mut(),
    };
    COUNTER_CALLBACK.store(ptr, Ordering::Release);
}

/// Emit a counter to the runner if one's registered, otherwise a
/// no-op. Cheap when off (one atomic load + null check).
///
/// `key` must not contain interior NULs; if it does the counter is
/// silently dropped (bad keys aren't worth crashing the bot).
pub fn emit_counter(key: &str, value: f64) {
    let ptr = COUNTER_CALLBACK.load(Ordering::Acquire);
    if ptr.is_null() {
        return;
    }
    // SAFETY: only ever set from a `CounterFn` value in
    // `__set_counter_callback`, so the transmute round-trips.
    let f: engine::CounterFn = unsafe { std::mem::transmute(ptr) };
    let Ok(cstr) = std::ffi::CString::new(key) else {
        return;
    };
    // SAFETY: `cstr.as_ptr()` is valid for the call; the callback
    // copies the contents out before returning.
    unsafe { f(cstr.as_ptr(), value) };
}

use std::{
    fmt::Display,
    io::{self, BufRead, Write},
    str::FromStr,
};

pub trait SingleLine {}

pub trait ReadFrom: Sized {
    fn read_from(r: &mut impl BufRead) -> anyhow::Result<Self>;
}

impl<T> ReadFrom for T
where
    T: FromStr + SingleLine,
    T::Err: Into<anyhow::Error>,
{
    fn read_from(r: &mut impl BufRead) -> anyhow::Result<Self> {
        let mut s = String::new();
        r.read_line(&mut s)?;
        s.parse().map_err(Into::into)
    }
}

// Output trait — takes any `Write` so the caller controls buffering.
//
// `io::stdout()` acquires its global mutex on every write call, and the
// returned handle is line-buffered on a TTY and block-buffered on a pipe, so
// raw `writeln!(io::stdout(), ...)` per line means one lock + (often) one
// syscall per line. The intended usage is to lock stdout once and wrap it in
// a `BufWriter` so all writes go through a single owned buffer:
//
//     let stdout = io::stdout().lock();
//     let mut out = io::BufWriter::new(stdout);
//     value.write_to(&mut out)?;
//     out.flush()?; // mandatory — buffered output is lost otherwise
//
// This gives line-by-line code without paying the per-line lock/syscall cost
// and without building an intermediate `String`.
pub trait WriteTo {
    fn write_to(&self, w: &mut impl Write) -> io::Result<()>;
}

impl<T> WriteTo for T
where
    T: Display + SingleLine,
{
    fn write_to(&self, w: &mut impl Write) -> io::Result<()> {
        writeln!(w, "{self}")
    }
}

// `()` impls — useful for games whose `InitialInput` is empty.
impl ReadFrom for () {
    fn read_from(_: &mut impl BufRead) -> anyhow::Result<Self> {
        Ok(())
    }
}

impl WriteTo for () {
    fn write_to(&self, _: &mut impl Write) -> io::Result<()> {
        Ok(())
    }
}

/// Define the FFI surface for a bot dynamic library.
///
/// Two-arg form (most bots — games whose `Defs::InitialInput = ()` or that
/// don't care about init data):
///
/// ```ignore
/// // tron_rs/src/lib.rs
/// pub fn decide(turn: tron_defs::TurnRef<'_>) -> tron_defs::TurnOutput { … }
/// common::ffi_bot!(tron_defs::Ffi, decide);
/// ```
///
/// Three-arg form (games with non-trivial `InitialInput` whose bots want
/// to inspect or stash it):
///
/// ```ignore
/// fn on_init(init: <chess_defs::Initial as common::WireInput>::Ref<'_>) {
///     // store init in a `OnceCell`, etc.
/// }
/// common::ffi_bot!(chess_defs::Ffi, decide, on_init);
/// ```
///
/// Generates four `extern "C"` exports — `initialize`, `take_turn`,
/// `abi_version`, `set_counter_callback` — each wrapped in
/// `catch_unwind` so a panic doesn't unwind across the FFI boundary
/// (UB). `set_counter_callback` is a no-op default; Rust bots that
/// want to emit performance counters today use the C++ pattern in
/// their own `bot.cpp` rather than going through this macro.
#[macro_export]
macro_rules! ffi_bot {
    ($defs:ty, $decide:expr) => {
        // Two-arg form: default init handler ignores its argument.
        $crate::ffi_bot!($defs, $decide, |_| ());
    };
    ($defs:ty, $decide:expr, $init:expr) => {
        #[unsafe(no_mangle)]
        pub extern "C" fn initialize(
            input: <<$defs as $crate::Defs>::InitialInput as $crate::WireInput>::Ffi<'_>,
        ) {
            // Bring the WireInputFfi trait into local scope so
            // `input.as_ref()` resolves without polluting the caller's
            // module-level namespace.
            use $crate::WireInputFfi as _;
            let _ = ::std::panic::catch_unwind(|| ($init)(input.as_ref()));
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn take_turn(
            input: <<$defs as $crate::Defs>::Input as $crate::WireInput>::Ffi<'_>,
        ) -> $crate::TurnResult<<$defs as $crate::Defs>::Output> {
            use $crate::WireInputFfi as _;
            match ::std::panic::catch_unwind(|| ($decide)(input.as_ref())) {
                Ok(output) => $crate::TurnResult {
                    status: $crate::BotStatus::Ok,
                    output,
                },
                Err(_) => $crate::TurnResult {
                    status: $crate::BotStatus::Panic,
                    output: ::std::default::Default::default(),
                },
            }
        }

        #[unsafe(no_mangle)]
        pub extern "C" fn abi_version() -> u32 {
            <$defs as $crate::Defs>::ABI_VERSION
        }

        /// Counter-callback hook. The runner passes a `CounterFn`
        /// pointer when `tournament --counters` is set; we stash
        /// it in `common`'s per-plugin static so subsequent
        /// `common::emit_counter("key", value)` calls forward to
        /// the runner. Bots that don't care about counters simply
        /// don't call `emit_counter`.
        #[unsafe(no_mangle)]
        pub extern "C" fn set_counter_callback(
            cb: ::std::option::Option<$crate::engine::CounterFn>,
        ) {
            $crate::__set_counter_callback(cb);
        }
    };
}
